name: Update README all day at 04:04

on:
  push:
  workflow_dispatch:
  schedule:
    # “At 13:37 on every day-of-week from Monday through Friday.”
    - cron: '* * * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Update README.md file
        run: |
          node index.js > README.md
        env:
          CI: true
      - name: Configure git
        run: |
          git config --global user.name 'Mickael Suard'
          git config --global user.email 'suard.mickael72@gmail.com'
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          add: 'README.md'
          message: ':memo: README.md updated by me'
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}